### ISSUE TITLE
'{DependencyProperty.UnsetValue}' is not a valid value for property 'FocusVisualStyle'

### ISSUE THREAD

**Issue by Nicks182** [AngryCarrot789/WPFDarkTheme#16]
This error keeps crashing my app while using the DarkTheme. I did find the source though. 

If I press the Tab key to change focus between controls, it will crash as soon as I try and change focus to a Checkbox.

I tried to see in the theme file if I can fix it, but I'm a noob when it comes to WPF styling. Hope you can help.

Below is stack trace from event viewer.

CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: '{DependencyProperty.UnsetValue}' is not a valid value for property 'FocusVisualStyle'.
   at System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   at System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.FrameworkElement.get_FocusVisualStyle()
   at System.Windows.Input.KeyboardNavigation.ShowFocusVisual(DependencyObject element)
   at System.Windows.Input.KeyboardNavigation.ShowFocusVisual()
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by Nicks182** [comment]
I fixed it. I had to move this Style to be above the checkbox style:
![image](https://user-images.githubusercontent.com/13113785/147383892-73fe5d8b-8636-4ba9-8a64-7f3339fd1394.png)

**Comment by bkht** [comment]
Thank you very much Nick!
That solved the same issue here!

**Comment by AngryCarrot789** [comment]
I fixed this for the newer update, where things like focus visuals used for most controls, are now defined at the top of the XAML file
